import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1.5rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        ivory: { DEFAULT: "hsl(var(--ivory-soft))", deep: "hsl(var(--ivory-deep))" },
        charcoal: { DEFAULT: "hsl(var(--charcoal-soft))", mute: "hsl(var(--charcoal-mute))" },
        gold: { DEFAULT: "hsl(var(--gold-accent))", glow: "hsl(var(--gold-glow))" },
        rose: { light: "hsl(var(--rose-light))" },
        fog: "hsl(var(--fog-layer))",
      },
      backgroundImage: {
        "gradient-cinematic": "var(--gradient-cinematic)",
        "gradient-focus": "var(--gradient-focus)",
        "gradient-fade-bottom": "var(--gradient-fade-bottom)",
        "gradient-fade-top": "var(--gradient-fade-top)",
        "gradient-vignette": "var(--gradient-vignette)",
        "gradient-gold": "var(--gradient-gold)",
      },
      boxShadow: {
        glass: "var(--shadow-glass)",
        soft: "var(--shadow-soft)",
        glow: "var(--shadow-glow)",
      },
      transitionTimingFunction: { cinema: "cubic-bezier(0.22, 1, 0.36, 1)" },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-up": { from: { opacity: "0", transform: "translateY(30px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "letter-in": { from: { opacity: "0", transform: "translateY(40px) scale(0.95)", filter: "blur(8px)" }, to: { opacity: "1", transform: "translateY(0) scale(1)", filter: "blur(0)" } },
        "float-up": { "0%": { transform: "translateY(100vh)", opacity: "0" }, "10%": { opacity: "0.7" }, "90%": { opacity: "0.5" }, "100%": { transform: "translateY(-10vh)", opacity: "0" } },
        "light-sweep": { "0%": { transform: "translateX(-100%) skewX(-20deg)" }, "100%": { transform: "translateX(200%) skewX(-20deg)" } },
        "pulse-glow": { "0%,100%": { boxShadow: "0 0 0 0 hsl(var(--gold-accent) / 0.6)" }, "50%": { boxShadow: "0 0 0 14px hsl(var(--gold-accent) / 0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 1s cubic-bezier(0.22, 1, 0.36, 1) both",
        "letter-in": "letter-in 1.4s cubic-bezier(0.22, 1, 0.36, 1) both",
        "float-up": "float-up linear infinite",
        "light-sweep": "light-sweep 3s cubic-bezier(0.22, 1, 0.36, 1) infinite",
        "pulse-glow": "pulse-glow 2.4s cubic-bezier(0.22, 1, 0.36, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
